// Runtime snapshot of all media references after assembly.
// Generated by GunAssemblyState.ResolveMedia().

using System.Collections.Generic;
using UnityEngine;

namespace GunAssemblyTool
{
    public class ResolvedMedia
    {
        // Merged lists from gun body + all equipped attachments.
        public List<AnimationClip> animations = new List<AnimationClip>();
        public List<AudioClip>     sfx        = new List<AudioClip>();
        public List<GameObject>    vfx        = new List<GameObject>();

        // Appends all non-null entries from a GunMediaData asset.
        public void Merge(GunMediaData src)
        {
            if (src == null) return;
            foreach (var c in src.animations) if (c != null) animations.Add(c);
            foreach (var c in src.sfx)        if (c != null) sfx.Add(c);
            foreach (var g in src.vfx)        if (g != null) vfx.Add(g);
        }
    }
}
