// Runtime snapshot of a fully assembled gun.
// Generated by GunAssemblyState.Build() after assembly is complete.
// Use this in de minigame to read stats, animations, sound and VFX.

using System.Collections.Generic;
using UnityEngine;

namespace GunAssemblyTool
{
    public class GunInstanceData
    {
        // ©¤©¤ Identity ©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤
        // The gun body this loadout is built on.
        public GunBodyData body;

        // All equipped attachments in slot order.
        public List<AttachmentData> attachments = new List<AttachmentData>();

        // ©¤©¤ Stats ©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤
        // Final computed numeric values (body base + all attachment bonuses).
        // Read this at runtime ¡ª do not modify after Build().
        public GunStats stats = new GunStats();

        // ©¤©¤ Media ©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤
        // Resolved animation, SFX and VFX references.
        // Body defaults are set first; attachment overrides replace matching entries.
        public ResolvedMedia media = new ResolvedMedia();

        // ©¤©¤ Convenience accessors ©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤©¤

        // Quick check whether this instance has any media at all.
        public bool HasMedia =>
            media.animations.Count > 0 ||
            media.sfx.Count > 0 ||
            media.vfx.Count > 0;

        // Total number of equipped attachments.
        public int AttachmentCount => attachments.Count;

        public override string ToString() =>
            $"[GunInstance] {body?.displayName ?? "No Body"} | " +
            $"{AttachmentCount} attachment(s) | {stats}";
    }
}